TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install)
# databases, templates, substitutions like this
DB += ADnED.template
DB += ADnEDChannel.template
DB += ADnEDDetector.template
DB += ADnEDDetectorPlugin.template
DB += ADnEDDetectorTOFPlugin.template
DB += ADnEDDetectorPixelPlugin.template
DB += ADnEDPixelROI.template
DB += ADnEDDetectorROIPluginASG.template
DB += ADnEDDetectorTOFROIScale.template
DB += ADnEDDetectorTOFMaskScale.template
DB += ADnEDDetectorROIRate.template
DB += ADnEDDetectorTOFTransform.template
DB += ADnEDMask.template
DB += ADnEDMaskN.template

#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_TEMPLATE = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

