TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

LIBRARY_IOC_Linux += mar345
LIBRARY_IOC_Darwin += mar345

LIB_SRCS += mar345.cpp
LIB_SRCS += mar3xx_pck.c

DBD += mar345Support.dbd

include $(ADCORE)/ADApp/commonLibraryMakefile

#=============================

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

